local_costmap:
  global_frame: "$(arg my_ns)/odom"
  robot_base_frame: "$(arg my_ns)/base_footprint"
  update_frequency: 4.0
  publish_frequency: 0.5
  static_map: false
  rolling_window: true
  width: 2.0
  height: 2.0
  # origin_x: -1.5
  # origin_y: -1.5
  resolution: 0.05
  inflation_radius: 0.3
