<?xml version="1.0"?>
<!-- iRobot Roomba 650 model -->
<robot name="roomba" xmlns:xacro="http://www.ros.org/wiki/xacro">

<!-- Change parameters in .gazebo and controller .yaml -->

  <xacro:property name="PI" value="3.141592"/>
  <xacro:property name="wheels_offset" value="0.235"/>
  <xacro:property name="wheels_xgap" value="0.04"/>
  <xacro:property name="wheels_radius" value="0.036"/>
  <xacro:property name="wheels_width" value="0.015"/>
  <xacro:property name="wheels_mass" value="0.7"/>
  <xacro:property name="wheels_damping" value="0.1"/>
  <xacro:property name="base_zgap" value="0.01"/>
  <xacro:property name="base_height" value="${0.083-base_zgap}"/>
  <xacro:property name="base_radius" value="0.174"/>
  <xacro:property name="base_mass" value="3.0"/>
  <xacro:property name="roller_radius" value="${base_zgap}"/>
  <xacro:property name="roller_xgap" value="0.135"/>
  <xacro:property name="ir_height" value="0.009"/>
  <xacro:property name="ir_radius" value="0.02"/>
  <xacro:property name="ir_xgap" value="0.15"/>
  <xacro:property name="lidar_radius" value="0.038"/>
  <xacro:property name="lidar_heigth" value="0.041"/>
  <xacro:property name="lidar_offset_y" value="0.105"/>


  <xacro:macro name="cylinder_inertial" params="radius length mass">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia ixx="${mass*radius*radius/2}" ixy="0.0" ixz="0.0"
               iyy="${mass*radius*radius/4+mass*length*length/12}" iyz="0.0" izz="${mass*radius*radius/4+mass*length*length/12}"/>
    </inertial>
  </xacro:macro>

  <xacro:include filename="$(find tfg_roomba)/urdf/roomba.gazebo" />
  <xacro:include filename="$(find tfg_roomba)/urdf/materials.xacro" />




  <link name="base">
    <xacro:cylinder_inertial
      radius="${base_radius}" length="${base_height}" mass="${base_mass}"/>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${base_radius}" length="${base_height}"/>
      </geometry>
      <material name="green_transparent"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${base_radius}" length="${base_height}"/>
      </geometry>
    </collision>
  </link>



  <joint name="lidar_joint" type="fixed">
    <origin xyz="0 ${lidar_offset_y} ${base_height/2+lidar_heigth/2}" rpy="0 0 0"/>
    <parent link="base"/>
    <child link="lidar"/>
  </joint>

  <link name="lidar">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.05"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
               iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_heigth}"/>
      </geometry>
      <material name="purple"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_heigth}"/>
      </geometry>
    </collision>
  </link>



  <joint name="roller_joint" type="fixed">
    <origin xyz="${roller_xgap} 0 ${-base_height/2}" rpy="0 0 0"/>
    <parent link="base"/>
    <child link="roller"/>
  </joint>

  <link name="roller">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.05"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
               iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${roller_radius}"/>
      </geometry>
      <material name="green_transparent"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${roller_radius}"/>
      </geometry>
    </collision>
  </link>



  <joint name="ir_joint" type="fixed">
    <origin xyz="${ir_xgap} 0 ${base_height/2+ir_height/2}" rpy="0 0 0"/>
    <parent link="base"/>
    <child link="ir"/>
  </joint>

  <link name="ir">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.01"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
               iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${ir_radius}" length="${ir_height}"/>
      </geometry>
      <material name="red"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${ir_radius}" length="${ir_height}"/>
      </geometry>
    </collision>
  </link>




  <link name="right_wheel">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${wheels_mass}"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${wheels_radius}" length="${wheels_width}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${wheels_radius}" length="${wheels_width}"/>
      </geometry>
    </collision>
  </link>



  <joint name="right_wheel_joint" type="continuous">
    <origin xyz="${-wheels_xgap} ${-wheels_offset/2} ${-base_zgap-base_height/2+wheels_radius}" rpy="${-PI/2} 0 0"/>
    <axis xyz="0 0 1"/>
    <parent link="base"/>
    <child link="right_wheel"/>
    <dynamics damping="${wheels_damping}"/>
  </joint>




  <link name="left_wheel">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.25"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${wheels_radius}" length="${wheels_width}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${wheels_radius}" length="${wheels_width}"/>
      </geometry>
    </collision>
  </link>



  <joint name="left_wheel_joint" type="continuous">
    <origin xyz="${-wheels_xgap} ${wheels_offset/2} ${-base_zgap-base_height/2+wheels_radius}" rpy="${-PI/2} 0 0"/>
    <axis xyz="0 0 1"/>
    <parent link="base"/>
    <child link="left_wheel"/>
    <dynamics damping="${wheels_damping}"/>
  </joint>


  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="right_wheel_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="left_wheel_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>





</robot>
