TrajectoryPlannerROS:
  max_vel_x: 0.3
  min_vel_x: -0.3
  max_vel_theta: 0.6
  min_vel_theta: -0.6
  min_in_place_vel_theta: 0.1

  acc_lim_theta: 10.0
  acc_lim_x: 10.0
  acc_lim_y: 10.0

  # gdist_scale: 5.0

  holonomic_robot: false

EBandPlannerROS:
  max_vel_lin: 0.3
  max_vel_th: 1.5
  min_vel_lin: 0.0
  min_vel_th: 0.0
  min_in_place_vel_th: 0.0
  # max_acceleration: 10.0
  max_translational_acceleration: 10.0
  max_rotational_acceleration: 10.0

  # Key parameters
  eband_internal_force_gain: 1.0
  eband_external_force_gain: 2.0   # Default 2.0

  differential_drive: true

  Ctrl_Rate: 10.0

  # disallow_hysteresis: true

TebLocalPlannerROS:
  footprint_model:
    type: "circular"
    radius: 0.174


  acc_lim_x: 20.0
  acc_lim_theta: 20.0
  max_vel_x: 0.3
  max_vel_x_backwards: 0.1
  # max_vel_theta: 4.25
  max_vel_theta: 1.0

  min_obstacle_dist: 0.05
  costmap_obstacles_behind_robot_dist: 0.1
  inflation_dist: 0.15

  map_frame: /map
