global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 1.0
  static_map: true
  resolution: 0.05
  inflation_radius: 0.4
  laser_scan_sensor: {sensor_frame: lidar, data_type: LaserScan, topic: /scan, marking: false, clearing: false}
