local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 0.5
  static_map: false
  rolling_window: true
  width: 2.0
  height: 2.0
  resolution: 0.05
  inflation_radius: 0.2

  laser_scan_sensor: {sensor_frame: lidar, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
