global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  transform tolerance: 0.1
  update_frequency: 10.0
  publish_frequency: 1.0
  # plugins:
  #   - {name: static, type: "costmap_2d::StaticLayer"}
  #   - {name: obstacles, type: "costmap_2d::ObstacleLayer"}
  #   - {name: inflation, type: "costmap_2d::InflationLayer"}
  #
  # static:
  #   map_topic: map
  #   subscribe_to_updates: true
  #
  # obstacles:
  #   observation_sources: laser_scan
  #   laser_scan: {sensor_frame: lidar, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
  #   rolling_window: true
  #   width: 4.0
  #   height: 4.0
  #   resolution: 0.05
  #   obstacle_range: 5.0
  #   raytrace_range: 5.0
  #   robot_radius: 0.174
  #
  # inflation:
  #   inflation_radius: 0.5
