local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint
  update_frequency: 10.0
  publish_frequency: 1.0
  static_map: false
  rolling_window: true
  width: 3.0
  height: 3.0
  resolution: 0.05
  # plugins:
  #   - {name: obstacles, type: "costmap_2d::ObstacleLayer"}
  #   - {name: inflation, type: "costmap_2d::InflationLayer"}
  #
  # obstacles:
  #   observation_sources: laser_scan
  #   laser_scan:
  #     sensor_frame: lidar
  #     data_type: LaserScan
  #     topic: /scan
  #     marking: true
  #     clearing: true
  #     max_obstacle_height: 2.0
  #     min_obstacle_height: -2.0
  #     obstacle_range:
  #
  #   rolling_window: true
  #   width: 4.0
  #   height: 4.0
  #   resolution: 0.05
  #   obstacle_range: 5.0
  #   raytrace_range: 5.0
  #   robot_radius: 0.174
  #
  # inflation:
  #   inflation_radius: 0.5
