global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  static_map: true
  update_frequency: 0.1
  publish_frequency: 0.1
  inflation_radius: 0.4
  resolution: 0.05
  obstacle_layer/enabled: false
